# Generated by Django 4.2.6 on 2023-11-30 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='desc',
            field=models.TextField(default='No Descriptions'),
        ),
    ]
