# Generated by Django 4.2.6 on 2023-12-03 00:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='bid_listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='auctions.listing'),
        ),
    ]
