# Generated by Django 4.2.6 on 2023-12-03 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='starting_price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
