# Generated by Django 4.2.6 on 2023-12-06 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0020_alter_listing_desc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_amout',
            new_name='bid_amount',
        ),
    ]
