# Generated by Django 4.2.6 on 2024-01-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0023_rename_watchlist_user_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
