# Generated by Django 4.2.6 on 2024-01-25 00:07

import auctions.models
from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=auctions.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(blank=True, default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Fvector-art%2F5337799-icon-image-not-found-vector&psig=AOvVaw1D619kvwycRDPZredTMalS&ust=1706227615437000&source=images&cd=vfe&opi=89978449&ved=0CBMQjRxqFwoTCPDJka2f94MDFQAAAAAdAAAAABAD', max_length=512, null=True),
        ),
    ]
