# Generated by Django 4.2.6 on 2024-01-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0025_alter_listing_image_alter_listing_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='image_url',
            field=models.CharField(blank=True, default='https://upload.wikimedia.org/wikipedia/commons/a/ac/No_image_available.svg', max_length=512, null=True),
        ),
    ]
