# Generated by Django 4.2.6 on 2023-12-22 04:10

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_alter_follow_follower_alter_follow_follower_count_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
                ('like_count', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='post',
            name='post_like_count',
        ),
    ]
