# Generated by Django 4.2.6 on 2023-12-22 09:58

from django.conf import settings
from django.db import migrations, models
import django_resized.forms
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_alter_post_managers_remove_post_post_like_count'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='follow',
            name='follower_count',
        ),
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=network.models.path_and_rename),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_like',
            field=models.ManyToManyField(blank=True, related_name='post_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
