# Generated by Django 4.2.6 on 2023-12-27 03:18

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_alter_post_managers_remove_follow_follower_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to=network.models.path_and_rename),
        ),
    ]
