# Generated by Django 4.2.6 on 2024-01-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_post_post_date_alter_post_post_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
